version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: todo_mongoDB
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - todo_mongo_data:/data/db
    networks:
      - todo_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo_backend
    restart: unless-stopped
    # ports:
    #   - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - todo_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # VITE_API_URL: http://localhost:8000/todos
        VITE_API_URL: "/todos"
    container_name: todo_frontend
    restart: unless-stopped
    # ports:
    #   - "5173:5173"
    depends_on:
      - backend
    # env_file:
    #   - ./frontend/.env
    networks:
      - todo_network

  ngnix:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: todo_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - todo_network

volumes:
  todo_mongo_data:

networks:
  todo_network:
    driver: bridge
