services:
  backend:
    build: ./backend
    container_name: todo_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    args: 
      VITE_API_URL: http://13.62.46.39:8000/todos
    container_name: todo_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
