name: build-and-list

# defines the events that trigger the workflow
# here we trigger the workflow on push or pull request events to the main branches
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# defines a job named build
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Lint backend code
        working-directory: backend
        run: npm run lint -- --max-warnings=0

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Lint frontend code
        working-directory: frontend
        run: npm run lint -- --max-warnings=0

  build:
    runs-on: ubuntu-latest
    needs: lint   # ensures lint passes before building
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build backend image
        run: docker build -t todo-backend ./backend

      - name: Build frontend image
        run: docker build -t todo-frontend ./frontend